M48
; DRILL file {KiCad (7.0.0)} date Mon May 15 22:46:24 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-15T22:46:24-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X125.476Y-19.748
X125.476Y-62.928
X145.796Y-19.748
X145.796Y-62.928
T0
M30
